/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#eaf1ff",
        "outline-variant": "#c6c6cd",
        "outline": "#76777d",
        "surface-variant": "#d3e4fe",
        "surface-container": "#e5eeff",
        "on-secondary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "tertiary": "#000000",
        "on-tertiary-fixed-variant": "#004c69",
        "tertiary-fixed-dim": "#7bd0ff",
        "error-container": "#ffdad6",
        "surface-container-low": "#eff4ff",
        "inverse-primary": "#bec6e0",
        "surface-container-highest": "#d3e4fe",
        "on-error-container": "#93000a",
        "primary-container": "#131b2e",
        "on-tertiary-container": "#008ebf",
        "inverse-surface": "#213145",
        "surface-tint": "#565e74",
        "on-surface-variant": "#45464d",
        "on-background": "#0b1c30",
        "on-primary-fixed-variant": "#3f465c",
        "tertiary-fixed": "#c4e7ff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#6bd8cb",
        "error": "#ba1a1a",
        "primary": "#000000",
        "text-warning": "#92400E",
        "surface": "#f8f9ff",
        "on-error": "#ffffff",
        "secondary-container": "#86f2e4",
        "on-tertiary": "#ffffff",
        "surface-accent": "#FEF3C7",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-container": "#7c839b",
        "background": "#f8f9ff",
        "secondary": "#006a61",
        "on-secondary-fixed": "#00201d",
        "on-primary-fixed": "#131b2e",
        "on-tertiary-fixed": "#001e2c",
        "tertiary-container": "#001e2c",
        "surface-dim": "#cbdbf5",
        "surface-main": "#F8FAFC",
        "primary-fixed": "#dae2fd",
        "surface-container-high": "#dce9ff",
        "secondary-fixed": "#89f5e7",
        "electric-blue": "#2563EB",
        "on-secondary-container": "#006f66",
        "on-surface": "#0b1c30",
        "on-secondary-fixed-variant": "#005049"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "stack-md": "16px",
        "element-gap": "16px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "section-gap": "80px",
        "stack-sm": "8px",
        "stack-lg": "32px"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-xl-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-xl-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "headline-lg": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
